#!/bin/sh

rm -f config.cache config.log acconfig.h aclocal.m4

(cd config && autoxt) || exit 1
(cd config && auto-java-front) || exit 1
aclocal -I config || exit 1
autoconf -f || exit 1
automake -a || exit 1
