#!/bin/sh

rm -f config.cache config.log acconfig.h aclocal.m4

os=$(uname -s)

if [ "$os" = "Linux" ]; then
    libtoolize
else
    glibtoolize
fi

autoxt || exit 1
aclocal -I . || exit 1
autoreconf -ifv || exit 1
automake -a || exit 1

echo
echo 'bootstrap complete.'
echo
echo 'Please resume the installation with:'
echo '  ./configure --prefix=<installation target> && make && make install'

