# Makefile.in generated by automake 1.10.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



###########################################################
# File: Makefile.xt
#
# autoxt
#
# Description
#
# This Makefile provides support for compiling Stratego 
# programs and use of some other XT tools.
#
###########################################################
#
# Variables
#


pkgdatadir = $(datadir)/webdsl
pkglibdir = $(libdir)/webdsl
pkgincludedir = $(includedir)/webdsl
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i386-apple-darwin9.7.0
host_triplet = i386-apple-darwin9.7.0
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/webdsls.pc.in \
	$(top_srcdir)/Makefile.xt $(top_srcdir)/configure AUTHORS \
	COPYING ChangeLog INSTALL NEWS TODO config/config.guess \
	config/config.sub config/depcomp config/install-sh \
	config/ltmain.sh config/missing
am__append_1 = -DDEFAULT_XTC_REPOSITORY="\"$(REPOSITORY)\""
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/autoxt.m4 \
	$(top_srcdir)/java-front.m4 $(top_srcdir)/pil.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = webdsls.pc
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(pkgconfigdir)"
pkgconfigDATA_INSTALL = $(INSTALL_DATA)
DATA = $(pkgconfig_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/missing --run aclocal-1.10
AMTAR = ${SHELL} /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/missing --run tar
AR = ar
ASFIX_TOOLS = $(STRATEGOXT)
ASF_LIBRARY = $(SDF)
ATERM = /nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238
ATERM_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include  
ATERM_FRONT = $(STRATEGOXT)
ATERM_LIBS = -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lATerm  
ATERM_STRCFLAGS = 
ATERM_XTC = 
AUTOCONF = ${SHELL} /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/missing --run autoconf
AUTOHEADER = ${SHELL} /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/missing --run autoheader
AUTOMAKE = ${SHELL} /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/missing --run automake-1.10
AWK = gawk
BUILD_REPOSITORY = /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/BUILDTIME_XTC
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CONCRETE_SYNTAX = $(STRATEGOXT)
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
C_TOOLS = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
C_TOOLS_CFLAGS = -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include  
C_TOOLS_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
C_TOOLS_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share/c-tools -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share/sdf/c-tools
C_TOOLS_XTC = 
DEFS = -DPACKAGE_NAME=\"webdsl\" -DPACKAGE_TARNAME=\"webdsl\" -DPACKAGE_VERSION=\"8.8\" -DPACKAGE_STRING=\"webdsl\ 8.8\" -DPACKAGE_BUGREPORT=\"webdsl@st.ewi.tudelft.nl\" -DPACKAGE=\"webdsl\" -DVERSION=\"8.8\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSIZEOF_VOID_P=4 -DSIZEOF_INT=4 -DSIZEOF_LONG=4 -DSIZEOF_DOUBLE=8 -DSVN_REVISION=\"2704\" -DHAVE_DLFCN_H=1
DEPDIR = .deps
DSYMUTIL = dsymutil
ECHO = /bin/echo
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = 
FFLAGS = 
GPP = $(STRATEGOXT)
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JAVA_FRONT = /nix/store/0ljfh92wkjv984ajvcc14pq154x1y775-java-front-0.9pre1823618236
JAVA_FRONT_CFLAGS =  
JAVA_FRONT_LIBS = /nix/store/0ljfh92wkjv984ajvcc14pq154x1y775-java-front-0.9pre1823618236/lib/libjava-front.la  
JAVA_FRONT_STRCFLAGS = -I /nix/store/0ljfh92wkjv984ajvcc14pq154x1y775-java-front-0.9pre1823618236/share/java-front-syntax -I /nix/store/0ljfh92wkjv984ajvcc14pq154x1y775-java-front-0.9pre1823618236/share/java-front -la /nix/store/0ljfh92wkjv984ajvcc14pq154x1y775-java-front-0.9pre1823618236/lib/libjava-front.la
JAVA_FRONT_XTC = /nix/store/0ljfh92wkjv984ajvcc14pq154x1y775-java-front-0.9pre1823618236/share/java-front/XTC
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/missing --run makeinfo
MKDIR_P = config/install-sh -c -d
NMEDIT = nmedit
OBJEXT = o
PACKAGE = webdsl
PACKAGE_BUGREPORT = webdsl@st.ewi.tudelft.nl
PACKAGE_NAME = webdsl
PACKAGE_STRING = webdsl 8.8
PACKAGE_TARNAME = webdsl
PACKAGE_VERSION = 8.8pre2704
PATH_SEPARATOR = :
PGEN = $(SDF)
PIL = /usr/local
PIL_CFLAGS =  
PIL_LIB = /usr/local/lib
PIL_LIBS =  
PIL_STRCFLAGS = 
PIL_XTC = 
PKG_CONFIG = /opt/local/bin/pkg-config
PT_SUPPORT = $(SDF)
RANLIB = ranlib
REPOSITORY = ${datarootdir}/webdsl/XTC
SCOMPILE = $(STRC)/bin/strc
SDF = /nix/store/nsqzbif08r11c518c67n8gss5rjh9d4h-sdf2-bundle-2.4pre212034
SDF_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include  
SDF_FRONT = $(STRATEGOXT)
SDF_LIBRARY = $(SDF)
SDF_LIBS = -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lATerm  
SDF_STRCFLAGS = 
SDF_TOOLS = $(STRATEGOXT)
SDF_XTC = 
SED = /usr/bin/sed
SET_MAKE = 
SGLR = $(SDF)
SHELL = /bin/sh
SRTS = $(STRATEGO_RUNTIME)
STRATEGOXT = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGOXT_CFLAGS =  
STRATEGOXT_LIBS =  
STRATEGOXT_STRCFLAGS = 
STRATEGOXT_XTC = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share/strategoxt/XTC
STRATEGO_ATERM = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_ATERM_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include  
STRATEGO_ATERM_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-aterm -lstratego-gpp -lstratego-sglr -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_ATERM_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-aterm.la
STRATEGO_ATERM_XTC = 
STRATEGO_FRONT = $(STRATEGOXT)
STRATEGO_GPP = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_GPP_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include  
STRATEGO_GPP_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-gpp -lstratego-sglr -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_GPP_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share/sdf/gpp -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-gpp.la
STRATEGO_GPP_XTC = 
STRATEGO_LIB = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_LIBRARIES = 
STRATEGO_LIB_CFLAGS = -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include  
STRATEGO_LIB_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_LIB_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-lib.la
STRATEGO_LIB_XTC = 
STRATEGO_REGULAR = $(STRATEGOXT)
STRATEGO_RTG = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_RTG_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include  
STRATEGO_RTG_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-rtg -lstratego-sglr -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_RTG_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-rtg.la
STRATEGO_RTG_XTC = 
STRATEGO_RUNTIME = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_RUNTIME_CFLAGS = -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include  
STRATEGO_RUNTIME_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-runtime -lm -lATerm  
STRATEGO_RUNTIME_STRCFLAGS = 
STRATEGO_RUNTIME_XTC = 
STRATEGO_SDF = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_SDF_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include  
STRATEGO_SDF_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-sdf -lstratego-aterm -lstratego-gpp -lstratego-sglr -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_SDF_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share  -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-sdf.la
STRATEGO_SDF_XTC = 
STRATEGO_SGLR = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_SGLR_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include  
STRATEGO_SGLR_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-sglr -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_SGLR_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-sglr.la
STRATEGO_SGLR_XTC = 
STRATEGO_TOOL_DOC = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_TOOL_DOC_CFLAGS = -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include  
STRATEGO_TOOL_DOC_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-tool-doc -lstratego-gpp -lstratego-sglr -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_TOOL_DOC_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-tool-doc.la
STRATEGO_TOOL_DOC_XTC = 
STRATEGO_XTC = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
STRATEGO_XTC_CFLAGS = -I/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/include -I/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/include  
STRATEGO_XTC_LIBS = -L/nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib -L/nix/store/wn1bq7f0ph1nxwzmr2pqm30a9yin4qjj-aterm-2.5pre21238/lib -lstratego-xtc -lstratego-lib -lstratego-lib-native -lstratego-runtime -lm -lATerm  
STRATEGO_XTC_STRCFLAGS = -I /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/share -la /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/lib/libstratego-xtc.la
STRATEGO_XTC_XTC = 
STRC = $(STRATEGOXT)
STRIP = strip
STR_CFLAGS =  -Wall -Wno-unused-label -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter
STR_LDFLAGS =  -bind_at_load
SVN_REVISION = 2704
VERSION = 8.8pre2704
XML_FRONT = $(STRATEGOXT)
XTC = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt
XTC_CFLAGS =  
XTC_LIBS = $(STRATEGO_XTC_LIBS)
XTC_PROG = /nix/store/amrry2l8wa4rrzn0hcn7qv7i16ypwamz-strategoxt/bin/xtc
XTC_STRCFLAGS = $(STRATEGO_XTC_STRCFLAGS)
XTC_XTC = 
abs_builddir = /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch
abs_srcdir = /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch
abs_top_builddir = /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch
abs_top_srcdir = /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = 
am__include = include
am__leading_dot = .
am__quote = 

# remove the default tar -o option to allow long path names
am__tar = ${AMTAR} chf - "$$tardir" 
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i386-apple-darwin9.7.0
build_alias = 
build_cpu = i386
build_os = darwin9.7.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i386-apple-darwin9.7.0
host_alias = 
host_cpu = i386
host_os = darwin9.7.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/config/install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_CFLAGS = $(STR_CFLAGS) $(am__append_1)
AM_LDFLAGS = $(STR_LDFLAGS)
AM_CPPFLAGS = $(STRATEGO_LIB_CFLAGS) $(STRATEGO_RUNTIME_CFLAGS) $(ATERM_CFLAGS)
LDADD = $(STRATEGO_LIB_LIBS) $(STRATEGO_RUNTIME_LIBS) $(ATERM_LIBS)

# backwards compatibilty: prefer STRATEGO_LIB_LIBS and STRATEGO_RUNTIME_LIBS in new code.
SSL_LIBS = $(ATERM_LIBS) $(STRATEGO_XTC_LIBS) $(STRATEGO_LIB_LIBS) $(STRATEGO_RUNTIME_LIBS) $(ATERM_LIBS)
STRATEGORUNLIBS = $(STRATEGO_RUNTIME_LIBS)
SUFFIXES = .str .cr .r .rtree .def .tbl .pp .sdf .rtg .rtg-nf .dfta
PARSESTRATEGO = $(STRATEGO_FRONT)/bin/parse-stratego
pkgconfigdir = $(libdir)/pkgconfig
sdfdatadir = $(datadir)/sdf/$(PACKAGE)
docdatadir = $(datadir)/doc/$(PACKAGE)

###########################################################
#
# Makerules for XTC
#
XTCFLAGS = -I $(XTC)/share/xtc 
DREPOSITORY = $(DESTDIR)$(REPOSITORY)
SUBDIRS = src src/org/webdsl/dsl/project test

#src/org/webdsl/dsl/generation
BOOTCLEAN_SUBDIRS = $(SUBDIRS)
DIST_SUBDIRS = $(SUBDIRS)
EXTRA_DIST = Makefile.xt bootstrap autoxt.m4 java-front.m4 webdsls.pc
CLEANFILES = XTC
ACLOCAL_AMFLAGS = -I.
pkgconfig_DATA = webdsls.pc
all: all-recursive

.SUFFIXES:
.SUFFIXES: .str .cr .r .rtree .def .tbl .pp .sdf .rtg .rtg-nf .dfta .c
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/Makefile.xt $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
webdsls.pc: $(top_builddir)/config.status $(srcdir)/webdsls.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(pkgconfigDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
	  $(pkgconfigDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(pkgconfigdir)/$$f"; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(pkgconfigdir)/$$f"; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
#all-local:
all-am: Makefile $(DATA) all-local
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(pkgconfigdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#install-data-local:
#install-exec-local:
clean: clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-libtool \
	distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am: install-data-local install-pkgconfigDATA

install-dvi: install-dvi-recursive

install-exec-am: install-exec-local

install-html: install-html-recursive

install-info: install-info-recursive

install-man:

install-pdf: install-pdf-recursive

install-ps: install-ps-recursive

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-pkgconfigDATA

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) install-am \
	install-strip

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am all-local am--refresh check check-am clean \
	clean-generic clean-libtool ctags ctags-recursive dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-zip distcheck distclean distclean-generic \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am \
	install-data-local install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-local install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-pkgconfigDATA install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-pkgconfigDATA


###########################################################
#
# Make rules for Stratego programs
#

.str.c : 
	$(SCOMPILE) $(STRINCLUDES) $(STRCFLAGS) $(SCFLAGS) -i $< -o $@ -c

.str.rtree :
	$(PARSESTRATEGO) $(STRINCLUDES) -i $< -o $@ 

.rtree.c : 
	$(SCOMPILE) $(STRINCLUDES) $(STRCFLAGS) $(SCFLAGS) -i $< -o $@ -c

bootclean-am: clean-am
	-test -z "$(BOOTCLEANFILES)" || rm -f $(BOOTCLEANFILES)

bootclean : bootclean-recursive

bootclean-recursive :
	@dot_seen=no; \
	target=bootclean; \
	list='$(BOOTCLEAN_SUBDIRS) .'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

###########################################################
#
# Makerules for SDF definitions
#

.sdf.def : 
	$(SDF_FRONT)/bin/pack-sdf $(SDFINCLUDES) -i $< -o $@ --dep $*.dep

.def.tbl :
	$(PGEN)/bin/sdf2table $(PGEN_FLAGS) -i $< -o $@ 

###########################################################
#
# Makerules for GPP
#

%.pp.af : %.pp
	$(GPP)/bin/parse-pp-table -i $< -o $@

.def.pp :
	@if [ ! -f ${srcdir}/$@ ]; then \
           $(GPP)/bin/ppgen -i $< -o $@ ;\
        else \
           $(GPP)/bin/parse-pp-table -i ${srcdir}/$@ -o $@.af ;\
           $(GPP)/bin/ppgen -t -i $< \
           | $(GPP)/bin/pptable-diff --old $@.af 2>&1 || \
                     eval "echo '## pptable-diff error: $@ is not consistent with syntax definition' >&2; exit 1";\
           touch $@ ;\
           $(RM) $@.af ;\
        fi

###########################################################
#
# Makerules for Stratego Regular
#

.def.rtg :
	$(STRATEGO_REGULAR)/bin/sdf2rtg $(SDF2RTG_FLAGS) -i $< -o $@

.rtg.str :
	$(STRATEGO_REGULAR)/bin/rtg2sig --module `basename "$*"` -i $< -o $@

.rtg.rtg-nf :
	$(STRATEGO_REGULAR)/bin/parse-rtg -i $< | \
	$(STRATEGO_REGULAR)/libexec/rtg-reduce | \
	$(STRATEGO_REGULAR)/libexec/rtg-group -o $@

.rtg.dfta :
	$(STRATEGO_REGULAR)/bin/rtg2dfta -i $< -o $@

relname:
	echo -n $(distdir) > relname

install-data-local::
	$(mkinstalldirs) `dirname $(DREPOSITORY)`
	@for file in fordummy $(XTC_IMPORT) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) import $$file ; \
	  echo $(XTC_PROG) -r $(DREPOSITORY) import $$file ; \
	done
	@for file in fordummy $(pkgdata_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(pkgdatadir) -V $(VERSION) -t `basename $$file` ; \
	done
	@for file in fordummy $(nobase_pkgdata_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(pkgdatadir) -V $(VERSION) -t $$file ; \
	done
	@for file in fordummy $(sdfdata_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(sdfdatadir) -V $(VERSION) -t `basename $$file` ; \
	done
	@for file in fordummy $(nobase_sdfdata_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(sdfdatadir) -V $(VERSION) -t $$file ; \
	done
	@for file in fordummy $(data_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(datadir) -V $(VERSION) -t `basename $$file` ; \
	done
	@for file in fordummy $(nobase_data_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(datadir) -V $(VERSION) -t $$file ; \
	done
	@echo "Data registered in repository $(DREPOSITORY): $(data_DATA) $(nobase_data_DATA) $(pkgdata_DATA) $(nobase_pkgdata_DATA) $(sdfdata_DATA) $(nobase_sdfdata_DATA)"

install-exec-local::
	$(mkinstalldirs) `dirname $(DREPOSITORY)`
	@for file in fordummy $(bin_PROGRAMS) $(bin_SCRIPTS) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(bindir) -V $(VERSION) -t `basename $$file $(EXEEXT)` ; \
	done
	@for file in fordummy $(libexec_PROGRAMS) $(libexec_SCRIPTS) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(DREPOSITORY) register -l $(libexecdir) -V $(VERSION) -t `basename $$file $(EXEEXT)` ; \
	done
	@echo "Tools registered in repository $(DREPOSITORY): $(bin_PROGRAMS) $(bin_SCRIPTS) $(libexec_PROGRAMS) $(libexec_SCRIPTS)"

all-local::
	@for file in fordummy $(XTC_IMPORT) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  $(XTC_PROG) -r $(BUILD_REPOSITORY) import $$file ; \
	  echo $(XTC_PROG) -r $(BUILD_REPOSITORY) import $$file ; \
	done
	@for file in fordummy $(data_DATA) $(pkgdata_DATA) $(sdfdata_DATA) $(bin_SCRIPTS) $(libexec_SCRIPTS); do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  if test -f "$$file"; then d="`pwd`"; else d="/Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch"; fi; \
	  $(XTC_PROG) -r $(BUILD_REPOSITORY) register -l "$$d" -V $(VERSION) -t `basename $$file` ; \
	done
	@for file in fordummy $(nobase_data_DATA) $(nobase_pkgdata_DATA) $(nobase_sdfdata_DATA) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  if test -f "$$file"; then d="`pwd`"; else d="/Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch"; fi; \
	  $(XTC_PROG) -r $(BUILD_REPOSITORY) register -l "$$d" -V $(VERSION) -t $$file ; \
	done
	@for file in fordummy $(bin_PROGRAMS) $(libexec_PROGRAMS) ; do \
	  if [ "$$file" = "fordummy" ]; then continue; fi; \
	  if test -f "$$file"; then d="`pwd`"; else d="/Domain/tudelft.net/Users/zhemel/svn/webdsl/pil-branch"; fi; \
	  $(XTC_PROG) -r $(BUILD_REPOSITORY) register -l "$$d" -V $(VERSION) -t `basename $$file $(EXEEXT)` ; \
	done
	@echo "Tools registered in repository $(BUILD_REPOSITORY): $(bin_PROGRAMS) $(bin_SCRIPTS) $(libexec_PROGRAMS) $(libexec_SCRIPTS)"
	@echo "Data registered in repository $(BUILD_REPOSITORY): $(data_DATA) $(nobase_data_DATA) $(pkgdata_DATA) $(nobase_pkgdata_DATA) $(sdfdata_DATA) $(nobase_sdfdata_DATA)"

###########################################################

cleaner : fullclean # alias

fullclean :
	$(MAKE) -C src cleaner

syntax :
	$(MAKE) -C src syntax

ctrees : 
	$(MAKE) -C src ctrees
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
