application: @@APPNAME@@
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /javascripts
  static_dir: javascripts
- url: /.*
  script: main.py

