#!/bin/sh 

rm -f config.cache config.log acconfig.h aclocal.m4

autoxt || exit 1
auto-java-front || exit 1
aclocal -I . || exit 1
autoconf -f || exit 1
automake -a || exit 1

echo
echo 'bootstrap complete.'
echo
echo 'Please resume the installation with:'
echo '  ./configure --prefix=<installation target> && make && make install'

