package utils;

//this class is meant to be overriden by WebDSL,
//a generated class with the same name and package will take precedence in classloader over this library class

public class TypesInfo {
	static String message = "Internal error: utils.TypesInfo should have been generated by the WebDSL compiler";
	static{
		System.out.println(message);
	}
	public static java.util.List<String> getStringCompatibleTypes()
    { 
    	throw new RuntimeException(message);
    }
}

