#!/bin/sh

echo "Be sure to run this script as root."
echo "Removing old index."
rm -rf @INDEXDIR@/@APPNAME@
echo "Creating new index, this may take a while."
ant -f build.reindex.xml
chmod -R 777 @INDEXDIR@/@APPNAME@
echo "Done."
