[
   Stylesheet                                   -- _1,
   Stylesheet.1:iter-star                       -- V vs=1[ _1 ],
   Ruleset                                      -- V[ V is=2[ H[ _1 KW["{"] ] _2 ] KW["}" ] ],
   Ruleset.1:iter-sep                           -- _1 KW[","],
   Ruleset.2:iter-star                          -- V[ _1 ],
   Page                                         -- KW["@Page"] _1 KW["{"] _2 KW["}"],
   Page.1:opt                                   -- _1,
   Page.2:iter-star-sep                         -- _1 KW[";"],
   PseudoPage                                   -- KW[":"] _1,
   CSSSelector                                     -- _1 _2,
   CSSSelector.2:iter-star                         -- _1,
   CSSSelector.2:iter-star.1:seq                   -- _1 _2,
   CSSSimpleSelector                               -- H hs=0[ _1 _2 ],
   CSSSimpleSelector.2:iter-star                   -- H hs=0[ _1 ],
   CSSSimpleSelector.2:iter-star.1:alt             -- _1 _2,
   CSSSimpleSelector.2:iter-star.1:alt.2:alt       -- _1 _2,
   CSSSimpleSelector.2:iter-star.1:alt.2:alt.2:alt -- _1 _2,
   CSSSimpleSelector                               -- _1,
   CSSSimpleSelector.1:iter                        -- _1,
   CSSSimpleSelector.1:iter.1:alt                  -- _1 _2,
   CSSSimpleSelector.1:iter.1:alt.2:alt            -- _1 _2,
   CSSSimpleSelector.1:iter.1:alt.2:alt.2:alt      -- _1 _2,
   Declaration                                  -- H[ H hs=0[ _1 KW[":"] ] H hs=0[ _2 _3 KW[";"] ] ],
   Declaration.3:opt                            -- _1,
   Property                                     -- _1,
   Expr                                         -- _1,
   Expr.1:iter                                  -- _1,
   Term                                         -- _1,
   Term.1:alt                                   -- _1 _1 _1 _1 _1 _1 _1 _1 _1 _1 _1 _1 _1,
   Uri                                          -- KW["url"] KW["("] _1 KW[")"],
   Hash                                         -- KW["#"] _1,
   Function                                     -- _1 KW["("] _2 KW[")"],
   CSSAdjacentSiblingCombinator                 -- KW["+"],
   CSSChildCombinator                           -- KW[">"],
   CSSDescendantCombinator						-- KW[" "],
   Operator                                     -- KW["/"],
   Operator                                     -- KW[","],
   Prio                                         -- KW["!"] KW["important"],
   Class                                        -- H hs=0[ KW["."] _1 ],
   ElementName                                  -- _1,
   ElementName                                  -- KW["*"],
   IdSelector                                   -- H hs=0[ KW["#"] _1 ],
   Attrib                                       -- KW["["] _1 _2 KW["]"],
   Attrib.2:opt                                 -- _1,
   Attrib.2:opt.1:seq                           -- _1 _2,
   Attrib.2:opt.1:seq.1:alt                     -- KW["="] _1,
   Attrib.2:opt.1:seq.1:alt.1:alt               -- KW["~="] KW["|="],
   Attrib.2:opt.1:seq.2:alt                     -- _1 _2,
   Pseudo                                       -- KW[":"] _1,
   Pseudo.1:alt                                 -- _1 _2,
   Pseudo.1:alt.2:seq                           -- KW["("] _1 KW[")"],
   Pseudo.1:alt.2:seq.1:opt                     -- _1
]
