[
   StringLit                   -- _1,
   IntLit                      -- _1,
   Var                         -- _1,
   Constructor                 -- _1 KW["{"] KW["}"],
   SetLit                      -- KW["{"] _1 KW["}"],
   SetLit.1:iter-sep           -- _1 KW[","],
   MethodCall                  -- _1 KW["."] _2 KW["("] _3 KW[")"],
   MethodCall.3:iter-star-sep  -- _1 KW[","],
   PropertyAccess              -- _1 KW["."] _2,
   IndexAccess                 -- _1 KW["["] _2 KW["]"],
   UnaryMinus                  -- KW["-"] _1,
   Not                         -- KW["!"] _1,
   Times                       -- _1 KW["*"] _2,
   Div                         -- _1 KW["/"] _2,
   Mod                         -- _1 KW["%"] _2,
   Plus                        -- _1 KW["+"] _2,
   Minus                       -- _1 KW["-"] _2,
   Eq                          -- _1 KW["=="] _2,
   NEq                         -- _1 KW["!="] _2,
   Gt                          -- _1 KW[">"] _2,
   Lt                          -- _1 KW["<"] _2,
   Leq                         -- _1 KW["<="] _2,
   Geq                         -- _1 KW[">="] _2,
   And                         -- _1 KW["&&"] _2,
   Or                          -- _1 KW["||"] _2,
   Assign                      -- _1 KW[":="] _2 KW[";"],
   ExpStat                     -- _1 KW[";"],
   ReturnPage                  -- KW["return"] _1 KW[";"],
   Block                       -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   Block.1:iter-star           -- _1,
   VarDecl                     -- KW["var"] _1 KW[":"] _2,
   VarDeclInit                 -- KW["var"] _1 KW[":"] _2 KW[":="] _3,
   Stat                        -- _1 KW[";"],
   For                         -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] _4,
   While                       -- KW["while"] KW["("] _1 KW[")"] _2,
   If                          -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   TemplateDef                 -- KW["define"] _1 _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   TemplateDef.1:iter-star     -- _1,
   TemplateDef.3:iter-star-sep -- _1 KW[","],
   TemplateDef.4:iter-star     -- _1,
   Page                        -- KW["page"],
   Param                       -- _1 KW[":"] _2,
   String                      -- _1,
   Call                        -- _1,
   CallArgs                    -- _1 KW["("] _2 KW[")"],
   CallArgs.2:iter-star-sep    -- _1 KW[","],
   CallElems                   -- _1 KW["{"] _2 KW["}"],
   CallElems.2:iter-star       -- _1,
   Call                        -- _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Call.2:iter-star-sep        -- _1 KW[","],
   Call.3:iter-star            -- _1,
   ForElem                     -- KW["for"] KW["("] _1 KW[":"] _2 KW["in"] _3 KW[")"] KW["{"] _4 KW["}"],
   ForElem.4:iter-star         -- _1,
   ForAllElem                  -- KW["for"] KW["("] _1 KW[":"] _2 KW[")"] KW["{"] _3 KW["}"],
   ForAllElem.3:iter-star      -- _1,
   Navigate                    -- KW["navigate"] _1 KW["{"] _2 KW["}"],
   Navigate.2:iter-star        -- _1,
   PageRef                     -- _1 KW["("] _2 KW[")"],
   PageRef.2:iter-star-sep     -- _1 KW[","],
   Action                      -- KW["action"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Action.2:iter-star-sep      -- _1 KW[","],
   Action.3:iter-star          -- _1,
   Submit                      -- KW["submit"] _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Submit.2:iter-star-sep      -- _1 KW[","],
   Submit.3:iter-star          -- _1,
   XmlElem                     -- KW["<"] _1 KW[">"] _2 KW["</"] _3 KW[">"],
   XmlElem.2:iter-star         -- _1,
   Elements                    -- KW["elements"],
   Init                        -- KW["init"] KW["{"] _1 KW["}"],
   Init.1:iter-star            -- _1,
   Rule                        -- KW["rule"] _1 _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   Rule.1:iter-star            -- _1,
   Rule.3:iter-star-sep        -- _1 KW[","],
   Page                        -- KW["page"],
   Action                      -- KW["action"],
   Template                    -- KW["template"],
   Entity                      -- KW["entity"] _1 KW["{"] _2 KW["}"],
   Entity.2:iter-star          -- _1,
   Property                    -- _1 KW[":"] _2,
   Property                    -- _1 KW[":"] _2 KW["("] _3 KW[")"],
   Property.3:iter-star-sep    -- _1 KW[","],
   Id                          -- KW["id"],
   Name                        -- KW["name"],
   Inverse                     -- KW["inverse"] KW[":"] _1,
   SimpleType                  -- _1,
   SetType                     -- KW["Set"] KW["<"] _1 KW[">"],
   Module                      -- KW["module"] _1 _2,
   Module.2:iter-star          -- _1
]