<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sdf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>SDF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(exports|hiddens|module|imports|sorts|lexical syntax|lexical restrictions|context-free restrictions|context-free syntax|variables)\b</string>
			<key>name</key>
			<string>keyword.control.sdf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%%.*$\n?</string>
			<key>name</key>
			<string>comment.line.sdf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sdf</string>
	<key>uuid</key>
	<string>3586D935-D82B-47B7-A1D5-0582A2E0F19C</string>
</dict>
</plist>
