<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>str</string>
	</array>
	<key>name</key>
	<string>Stratego</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(module|imports|rules|strategies|where)\b</string>
			<key>name</key>
			<string>keyword.other.stratego</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|end|not|fail)\b</string>
			<key>name</key>
			<string>keyword.control.stratego</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;[^&gt;]+&gt;</string>
			<key>name</key>
			<string>support.function.ruleapplication.stratego</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;+|;</string>
			<key>name</key>
			<string>keyword.operator.stratego</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z][A-Za-z]*\([^\)]*\)</string>
			<key>name</key>
			<string>support.class.constructor.stratego</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([a-z\-]+|[A-Z][A-Za-z]*)(\([^\)]*\))?\s*(:|=)</string>
			<key>name</key>
			<string>constant.other.rule.stratego</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(java|bstm\*?|class-body-dec\*?)\s*\|\[</string>
			<key>end</key>
			<string>\]\|</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%&gt;</string>
			<key>end</key>
			<string>&lt;%</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>webdsl\|\[</string>
			<key>end</key>
			<string>\]\|</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.webdsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$\n?</string>
			<key>name</key>
			<string>comment.line.stratego</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.stratego</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.stratego</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.stratego</string>
	<key>uuid</key>
	<string>C319B6E6-2BE2-45DC-B0E9-815950B76F01</string>
</dict>
</plist>
