<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>app</string>
	</array>
	<key>name</key>
	<string>WebDSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>description\s*\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>comment.block.description.webdsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(application|imports|section|if|else|for|in|return|define|var|page|email|enum|session|entity|extend entity|predicate|policy|pointcut|access control rules|rules|globals|action|function|template|where|order by|init|goto|operation|who|when|do|view|derive)\b</string>
			<key>name</key>
			<string>keyword.other.webdsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|this|Bool|String|Int|Float|Bool|Secret|Email|Text|WikiText|Date|Time|DateTime|Patch|Image|File|URL|Set|List|inverse|status|securityContext)\b</string>
			<key>name</key>
			<string>constant.language.webdsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(title|section|header|form|table|row|list|listitem|captcha|output|input|select|navigate|url|menu|menuheader|menuitem|menubar|block|par|to|from|subject)\b</string>
			<key>name</key>
			<string>constant.other.webdsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$\n?</string>
			<key>name</key>
			<string>comment.line.webdsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.webdsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.webdsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.webdsl</string>
	<key>uuid</key>
	<string>9F825397-2F60-42AB-B082-80E9D4305194</string>
</dict>
</plist>
