webdsl.email.host=@SMTPHOST@
webdsl.email.port=@SMTPPORT@
webdsl.email.user=@SMTPUSER@
webdsl.email.pass=@SMTPPASS@
webdsl.email.authenticate=@SMTPAUTHENTICATE@
webdsl.email.protocol=@SMTPPROTOCOL@
webdsl.email.starttls=@SMTPSTARTTLS@
webdsl.email.sslprotocols=@SMTPSSLPROTOCOLS@
webdsl.email.debug=@SMTPDEBUG@