#!/bin/bash

# Author: Zef Hemel (zef@zefhemel.com)

echo "Loading application settings (application.ini)"
. application.ini

export WEBDSLPATH=`dirname $0`/../../../../..
export DSLTOSEAM=$WEBDSLPATH/src/org/webdsl/dsl/generation/dsl-to-seam

export ESCAPED_DSLTOSEAM=`echo $DSLTOSEAM | sed 's/\\//\\\\\\//g'`
export ESCAPED_JBOSSPATH=`echo $JBOSSPATH | sed 's/\\//\\\\\\//g'`

echo Making empty application
rm -rf .app
mkdir .app
cd .app
tar xzf $WEBDSLPATH/src/org/webdsl/dsl/project/template.tar.gz
mv resources/GENERICAPP-prod-ds.xml resources/$APPNAME-prod-ds.xml
mv resources/GENERICAPP-dev-ds.xml resources/$APPNAME-dev-ds.xml
find . -type f \! -iname \*.jar -exec sh -c 'sed -e "s/@@JBOSSPATH@@/$ESCAPED_JBOSSPATH/g" -e "s/@@DBPASSWORD@@/$DBPASSWORD/g" -e "s/@@DBUSER@@/$DBUSER/g" -e "s/@@DBNAME@@/$DBNAME/g" -e "s/@@DBSERVER@@/$DBSERVER/g" -e "s/@@APPNAME@@/$APPNAME/g" -e "s/@@DSLTOSEAM@@/$ESCAPED_DSLTOSEAM/g" $0 > $0.new && mv $0.new $0' {} \;

echo Copying your application files
find .. \( ! -regex '.*/\..*' \) -type f -name '*.app' -exec cp {} app \;
find .. \( ! -regex '.*/\..*' \) -type f -name '*.css' -exec cp {} view/stylesheet \;

case "$1" in
  "-c" )
     echo Compiling your application to Java only
     make
     ;;
  * )
     echo Compiling and deploying your application
     make && ant
     ;;
esac

echo Done!
echo "Result application is in .app, in case you're interested"
