#!/bin/bash

# Author: Zef Hemel (zef@zefhemel.com)

export JBOSSPATH=/home/zef/jboss

echo -n "Application name (one word): "
read APPNAME
export APPNAME

echo -n "MySQL Host [localhost]: "
read DBSERVER
if [ "$DBSERVER" == "" ]
then
   DBSERVER=localhost
fi
export DBSERVER

echo -n "MySQL Username [visser]: "
read DBUSER
if [ "$DBUSER" == "" ]
then
   DBUSER=visser
fi
export DBUSER

echo -n "MySQL Password [dsl]: "
read DBPASSWORD
if [ "$DBPASSWORD" == "" ]
then
   DBPASSWORD=dsl
fi
export DBPASSWORD

echo -n "MySQL Databse [serg]: "
read DBNAME
if [ "$DBNAME" == "" ]
then
   DBNAME=serg
fi
export DBNAME

echo -n "JBoss path for deployment [$JBOSSPATH]: "
read BOSSPATH
if [ "$BOSSPATH" == "" ]
then
   BOSSPATH=$JBOSSPATH
fi
export JBOSSPATH=$BOSSPATH

export WEBDSLPATH=`dirname $0`/../../../../..
export DSLTOSEAM=$WEBDSLPATH/src/org/webdsl/dsl/generation/dsl-to-seam

export ESCAPED_DSLTOSEAM=`echo $DSLTOSEAM | sed 's/\\//\\\\\\//g'`
export ESCAPED_JBOSSPATH=`echo $JBOSSPATH | sed 's/\\//\\\\\\//g'`

mkdir $APPNAME
cd $APPNAME
tar xzf $WEBDSLPATH/src/org/webdsl/dsl/project/template.tar.gz
mv resources/GENERICAPP-prod-ds.xml resources/$APPNAME-prod-ds.xml
mv resources/GENERICAPP-dev-ds.xml resources/$APPNAME-dev-ds.xml
find . -type f \! -iname \*.jar -exec sh -c 'sed -e "s/@@JBOSSPATH@@/$ESCAPED_JBOSSPATH/g" -e "s/@@DBPASSWORD@@/$DBPASSWORD/g" -e "s/@@DBUSER@@/$DBUSER/g" -e "s/@@DBNAME@@/$DBNAME/g" -e "s/@@DBSERVER@@/$DBSERVER/g" -e "s/@@APPNAME@@/$APPNAME/g" -e "s/@@DSLTOSEAM@@/$ESCAPED_DSLTOSEAM/g" $0 > $0.new && mv $0.new $0' {} \;

echo Done!
