#!/bin/bash

file=$1.nwl
if [ ! -f $file ]; then
	echo "Cannot find file: $file"
	echo "Usage: $0 file"
	exit
fi

rm -rf .nwl-cache
./compile-make
touch $1.nwl
./make &> out.txt
echo "Created out.txt" 
