<?php

function makeVersion($file, $version) {
  $template = $file . ".template.nwl";
  if (file_exists($template)) {
    exec("php ../create.php $template $file.nwl 2");
  }
}

function compile($file) {
  
  echo "Testing: $file\n";
  
  $filename = $file . ".nwl";
  if (!makeVersion($file, "2")) {
    touch($filename); // force compilation
  }
  sleep(1); // Too fast otherwise.. timestamps of cache == timestamp of file
  $cmd = "/home/nathan/nwl/trans/nwlj --verbose 2 -i $filename 2>&1 ";
	exec($cmd, $output, $ret);
	if ($ret !== 0) {
	 echo("Error executing: $cmd\n");
	 echo(implode("\n", $output));
	 echo("\n");
	 die();
	}
	$data = array();
	$data['written'] = array();
	$data['files'] = array();
	foreach($output as $line) {
		if (preg_match("_Write file (.*):[ ]*\.generated/(.*)\.java_", $line, $matches)) {
			$data['written'][$matches[2]] = array('type' => $matches[1]);
			array_push($data['files'], $matches[2]);
		}
	}
	//echo "---\n\n";
	//echo implode("\n", $output);
	makeVersion($file, "1");
	return $data;

}

function checkFiles($title, $data, $files) {
	foreach($data['files'] as $file) {
		if (!in_array($file, $files)) {
			echo "$title: File should not be written to: $file\n";
		}
	}
	foreach($files as $file) {
		if (!in_array($file, $data['files'])) {
			echo "$title: File should be written to: $file\n";
		}
	}
	foreach($data['written'] as $file => $w) {
	  if ($w['type'] == 'new') {
	    echo "$title: File has changed: $file\n";
	  }
	} 
}

// Fresh start
exec("./clean");
compile("main");

// Test 1: if entity Entry changed, its view page must also be recompiled
$data = compile("data");
checkFiles("Test:data", $data, array("Entry", "view_Entry", "login"));

// Test 2: if access control has changed, recompile all templates + pages
// Also, the view page generated by the Entity has to be recompiled, so entity is touched as well. 
$data = compile("ac");
checkFiles("Test:ac", $data, array("main", "main134", "root", "login", "pred_ac_AccessControlRule_3_8", "pred_ac_AccessControlRule_3_9", "pred_ac_AccessControlRule_3_10", "pred_ac_AccessControlRule_3_14", "Entry", "view_Entry"));

// Test 3: if page access control has changed, recompile all pages, including view page
$data = compile("pageac");
checkFiles("Test:pageacl", $data, array("root", "login", "pred_pageac_AccessControlRule_3_8", "Entry", "view_Entry"));

// Test 4: if logging has changed, recompile entity and its generated view page
$data = compile("logging");
checkFiles("Test:logging", $data, array("Entry", "login", "view_Entry"));

?>
